files:
  - path: docs/en/**/*.md
    dictionary: en_US
    customDictionary: .shared-scripts/dictionaries/bw-dict-en.txt
  - path: docs/fr/**/*.md
    dictionary: fr_FR
    customDictionary: .shared-scripts/dictionaries/bw-dict-fr.txt
  - path: docs/de/**/*.md
    dictionary: de_DE
    customDictionary: .shared-scripts/dictionaries/bw-dict-de.txt
  - path: docs/es/**/*.md
    dictionary: es_ES
    customDictionary: .shared-scripts/dictionaries/bw-dict-es.txt
  - path: docs/ru/**/*.md
    dictionary: ru_RU
    customDictionary: .shared-scripts/dictionaries/bw-dict-ru.txt

excludeFiles:
  - "vendor/**"
  - "node_modules/**"
  - ".git/**"
