name: SpellCheck

on:
  push:
    paths:
      - 'docs/**.md'
  pull_request:
    paths:
      - 'docs/**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # Ensures submodules are checked out!
      - name: Spellcheck Documentation
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          config_path: .github/spellcheck.yml
